version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/pkg/db"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/pkg/logger"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/proxy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/system-metrics"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/page"
    schedule:
      interval: "weekly"
